import re

def validate_output(response: str) -> str:
    """
    Validate the final response generated by the LLM before sending it to the user.
    Returns a safe fallback if the response violates policy.
    """
    if not response:
        return "I am unable to generate a valid response at this time."
        
    # Check for leaked secrets or internal tokens (primitive check)
    if "mock-internal-token-secret" in response:
        return "Response blocked: Safety violation (Code: OUT-SEC-01)."
        
    # Check for obvious internal IPs (e.g. 10.x.x.x, 192.168.x.x)
    internal_ip_pattern = re.compile(r'(10\.\d+\.\d+\.\d+|192\.168\.\d+\.\d+|172\.(1[6-9]|2[0-9]|3[0-1])\.\d+\.\d+)')
    if internal_ip_pattern.search(response):
        return "Response blocked: Internal infrastructure details cannot be disclosed."
        
    return response

